name: ShulkerPacksContinued
version: 1.6.4
main: io.shantek.ShulkerPacksContinued
api-version: 1.13

commands:
  shulkerpacks:
    usage: /<command> reload
    description: reloads the shulkerpacks config
    permission: op

permissions:
  shantek.shulkerpacks.use:
    description: gives player permission to open shulker boxes in their inventory
    default: op
  shantek.shulkerpacks.air:
    description: allows the player to open the shulkerbox in the air (if config enables it) if the player has "shantek.shulkerpacks.use"
    default: true
  shantek.shulkerpacks.inventory:
    description: allows the player to open the shulkerbox in their inventory (if config enables it) if the player has "shantek.shulkerpacks.use"
    default: true
  shantek.shulkerpacks.chests:
    description: allows the player to open the shulkerbox in a chest (if config enables it) if the player has "shantek.shulkerpacks.use"
    default: true
